# Generated by Django 4.2.17 on 2025-01-03 17:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workflow_config", "0007_alter_channel_id_alter_function_channel_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="channel",
            options={"verbose_name": "Channel", "verbose_name_plural": "Channels"},
        ),
    ]
