# Generated by Django 4.2.17 on 2025-01-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow_config", "0015_alter_template_actor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="template",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
