# Generated by Django 4.2.17 on 2025-01-08 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("workflow_config", "0016_alter_template_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="function",
            name="template",
        ),
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "function",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_templates",
                        to="workflow_config.function",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_templates",
                        to="workflow_config.template",
                    ),
                ),
            ],
            options={
                "verbose_name": "NotificationTemplate",
                "verbose_name_plural": "NotificationTemplates",
            },
        ),
    ]
