# Generated by Django 4.2.17 on 2025-01-03 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("newname", "0005_alter_channel_id_alter_function_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="function",
            name="channel",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="functions",
                to="newname.channel",
                verbose_name="Channel",
            ),
        ),
    ]
