# Generated by Django 5.0.9 on 2024-12-20 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0002_auto_20241220_1632"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onapprovedhook",
            name="callback_function",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_hooks",
                to="workflow.function",
                verbose_name="Function",
            ),
        ),
        migrations.AlterField(
            model_name="onapprovedhook",
            name="workflowmodel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_hooks",
                to="workflow.workflowmodel",
                verbose_name="WorkflowModel",
            ),
        ),
        migrations.AlterField(
            model_name="oncompletehook",
            name="callback_function",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_hooks",
                to="workflow.function",
                verbose_name="Function",
            ),
        ),
        migrations.AlterField(
            model_name="oncompletehook",
            name="workflowmodel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_hooks",
                to="workflow.workflowmodel",
                verbose_name="WorkflowModel",
            ),
        ),
        migrations.AlterField(
            model_name="ontransithook",
            name="callback_function",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_hooks",
                to="workflow.function",
                verbose_name="Function",
            ),
        ),
        migrations.AlterField(
            model_name="ontransithook",
            name="workflowmodel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_hooks",
                to="workflow.workflowmodel",
                verbose_name="WorkflowModel",
            ),
        ),
    ]
