# Generated by Django 4.2.17 on 2025-01-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0003_alter_onapprovedhook_callback_function_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("template", models.CharField(max_length=500)),
            ],
            options={
                "verbose_name_plural": "Channels",
            },
        ),
    ]
