# Generated by Django 4.2.17 on 2025-01-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0009_populates_channel_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="number_of_variables",
            field=models.IntegerField(default=0),
        ),
    ]
