# Generated by Django 4.2.17 on 2025-01-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0018_alter_notificationtemplate_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='text',
            field=models.TextField(help_text='You can use variables like {{borrower_name}} and {{seller_name}} which will be automatically replaced with the corresponding value.'),
        ),
    ]
