# Generated by Django 4.2.17 on 2025-01-15 17:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0019_alter_template_text"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workflowmodel",
            options={
                "verbose_name": "Workflow Model",
                "verbose_name_plural": "Workflow Models",
            },
        ),
    ]
