# Generated by Django 4.2.17 on 2025-01-29 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0021_alter_template_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="transitionmeta",
            name="is_return_transition",
            field=models.BooleanField(
                default=False, verbose_name="Is Return Transition"
            ),
        ),
    ]
