# Generated by Django 4.2.17 on 2025-02-17 20:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0022_transitionmeta_is_return_transition"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="subject",
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
    ]
