# Generated by Django 5.0.9 on 2025-03-06 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0027_emaillayout'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActorEmailLayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actors_email_layouts', to='workflow.actor')),
                ('email_layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_layout_actors', to='workflow.emaillayout')),
            ],
            options={
                'verbose_name': 'Actor Email Layout',
                'verbose_name_plural': 'Actor Email Layouts',
                'unique_together': {('actor', 'email_layout')},
            },
        ),
    ]
