# Generated by Django 5.0.9 on 2025-03-06 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0028_actoremaillayout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emaillayout',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='emaillayout',
            name='subject',
        ),
    ]
