# Generated by Django 4.2.17 on 2025-03-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0029_remove_emaillayout_actor_remove_emaillayout_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='action_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
