# Generated by Django 4.2.17 on 2025-06-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0032_alter_template_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="template",
            name="text",
            field=models.TextField(
                help_text="\n        You can use variables like {trader_name} and {barn_manager_name} which will be automatically replaced with the corresponding value.\n        <ul>\n            <li>Use {trader_name} for the borrower's name</li>\n            <li>Use {barn_manager_name} for the seller's name</li>\n            <li>Use {amount} for the trade amount</li>\n            <li>Use {trade_id} for the trade ID</li>\n            <li>Use {trade_title} for the trade title</li>\n            <li>Use {trade_date} for the trade date</li>\n            <li>Use {status} for the trade status</li>\n            <li>Use {due_date} for the trade due date</li>\n        </ul>\n        *Note: {days_delta} to be used only on Task Templates, it represents the number of days between the trade payback date and the current date.\n        <br>\n        **Important: Internal Notifications should not exceed 130 characters.\n        "
            ),
        ),
    ]
