# Generated by Django 4.2.17 on 2025-01-06 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("river", "0010_channel_number_of_variables"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onapprovedhook",
            name="hook_type",
            field=models.CharField(
                choices=[("BEFORE", "Before"), ("AFTER", "After")],
                default=("AFTER", "After"),
                max_length=50,
                verbose_name="When?",
            ),
        ),
        migrations.AlterField(
            model_name="oncompletehook",
            name="hook_type",
            field=models.CharField(
                choices=[("BEFORE", "Before"), ("AFTER", "After")],
                default=("AFTER", "After"),
                max_length=50,
                verbose_name="When?",
            ),
        ),
        migrations.AlterField(
            model_name="ontransithook",
            name="hook_type",
            field=models.CharField(
                choices=[("BEFORE", "Before"), ("AFTER", "After")],
                default=("AFTER", "After"),
                max_length=50,
                verbose_name="When?",
            ),
        ),
    ]
