# Generated by Django 4.2.17 on 2025-01-06 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("river", "0012_alter_onapprovedhook_hook_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="channel",
            name="number_of_variables",
        ),
        migrations.RemoveField(
            model_name="channel",
            name="template",
        ),
        migrations.RemoveField(
            model_name="function",
            name="channel",
        ),
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("text", models.TextField()),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="river.channel"
                    ),
                ),
            ],
            options={
                "verbose_name": "Template",
                "verbose_name_plural": "Templates",
            },
        ),
        migrations.AddField(
            model_name="function",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="functions",
                to="river.template",
                verbose_name="Template",
            ),
        ),
    ]
