# Generated by Django 4.2.17 on 2025-01-06 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("river", "0013_remove_channel_number_of_variables_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Actor",
                "verbose_name_plural": "Actors",
            },
        ),
        migrations.AddField(
            model_name="template",
            name="actor",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="river.actor"
            ),
        ),
    ]
