# Generated by Django 4.2.17 on 2025-01-06 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("river", "0014_actor_template_actor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="template",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="river.actor",
            ),
        ),
    ]
