# Generated by Django 4.2.17 on 2025-01-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("river", "0015_alter_template_actor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onapprovedhook",
            name="hook_type",
            field=models.CharField(
                choices=[("BEFORE", "Before"), ("AFTER", "After")],
                max_length=50,
                verbose_name="When?",
            ),
        ),
        migrations.AlterField(
            model_name="oncompletehook",
            name="hook_type",
            field=models.CharField(
                choices=[("BEFORE", "Before"), ("AFTER", "After")],
                max_length=50,
                verbose_name="When?",
            ),
        ),
        migrations.AlterField(
            model_name="ontransithook",
            name="hook_type",
            field=models.CharField(
                choices=[("BEFORE", "Before"), ("AFTER", "After")],
                max_length=50,
                verbose_name="When?",
            ),
        ),
    ]
