# Generated by Django 4.2.17 on 2025-01-08 17:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("river", "0017_remove_function_template_notificationtemplate"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notificationtemplate",
            options={
                "verbose_name": "Notification Template",
                "verbose_name_plural": "Notification Templates",
            },
        ),
    ]
